EmbarkStudios/emote

.github/workflows/pre-release.yaml
This ensures the nightly release points to the proper tag and contents. Previously they'd keep old files and the sha wasn't getting updated.
I noticed it's containing the wrong changelog; I think that's an upstream bug that'll resolve when we release the next version.
=> Ensure `latest` tag has proper contents and commit

plugins/pdm-plugin-torch/src/pdm_plugin_torch/config.py, plugins/pdm-plugin-torch/src/pdm_plugin_torch/main.py, pyproject.toml
This allows emit to use the same plugin to pull in `torch` and `torchvision` together.
=> allow specifying multiple dependencies for pdm-plugin-torch

.buildkite/Dockerfile, .buildkite/install-repo.sh, .buildkite/pipeline.yml, .buildkite/publish-docs.sh
Noticied when working on $OTHER_REPO that there's some wonkiness with how we install gcloud and setup our CI tasks that leads to subpar performance. This change should have very little impact on regular running but when the builds cluster is under heavy load we'll not degrade as heavily as we have in the past.
In practice we have ended up running on "any" resource available. I noticed this because we had crammed a bunch of pytest runners into a single available CPU slot, causing some 10-second checks to run for 10+ minutes.
=> Optimize CI performance with preinstalls and dedicated CPU

CHANGELOG.md, docs/installing-torch.rst, pdm.lock, pyproject.toml, torch.lock
When consumed as a dependency, the library does not correctly pin to a CPU version of cuda.
=> rename torch-cpu feature

.buildkite/requirements.txt
This is handled with the optional group nowadays.
This showed up in a Dependabot security scan and causes issues there.
=> remove unused file

CHANGELOG.md, emote/callback.py, emote/trainer.py, tests/test_trainer.py
I think we talked about what cycle 0 means before @singhblom but I added a bug in the OnnxExporter by default to None instead of 0. And I think that is *more* correct as a value for "don't run".
=> allow None in cycle to disable

docs/documentation.md, docs/index.rst, pyproject.toml
Adds a documentation page about working with documentation in different formats. Also adds two short commands (both in docs and pyproject) to work with docs files.
=> Add documentation about writing docs

emote/__init__.py, emote/callbacks.py, emote/extra/onnx_exporter.py, emote/extra/system_logger.py, emote/memory/callbacks.py, emote/sac.py, experiments/gym/train_carracing.py, tests/gym/collector.py
This changes LoggingCallback to be a mixin class instead. This decouples it from the callback system, making it reusable as a baseclass for proxies and other objects that live on the inference side.
=> refactor LoggingCallback to LoggingMixin

.gitignore
Updating with PDM caused me to have 10k new files to add in git. Ignoring __pypackages__ seems sensible.
=> Ignore pypackages

emote/sac.py
When trying to load a state dictionary for the alpha loss (e.g. from checkpoints), there was a problem with a None value being assigned. This came from a missing return statement in the function where the state dictionary is loaded, which is added here.
=> Missing return statement in AlphaLoss

emote/models/callbacks.py, emote/models/model_env.py
Currently, input_key is hard-coded to "obs" for all mbrl functionalities. The new changes enable choosing input_keys as an extra arguments to the corresponding classes.
=> fixed the input_key error

emote/memory/table.py, tests/test_memory_exporter.py
atomic_writes (which is also unmaintained nowadays! 😱) unfortunately has restrictive permissions. By default, it'll only allow the owner to read or write. This is overly restrictive and sometimes leads to errors during cloud training.
This PR ensures we expand those permissions to `u+rw g+w o+w`.
=> ensure memory exports are readable everywhere

emote/nn/gaussian_policy.py
The current implementation of the action sampling using _RobustTanhTransform_ causes some numerical instability. This leads to the log probability getting extreme values, which then completely destabilizes the training and the creature fails to learn.
_TanhTransform_ with cache_size=1 caches the original action values sent to the transform and returns them instead of doing the inverse transformation, which seems to prevent the instability issue. The results are in line with Cog training runs, and the creature is able to learn the tasks.
=> Hyperbolic tangent instability

emote/extra/onnx_exporter.py
Otherwise client-triggered exports won't be processed leading to network timeouts.
=> ensure pending exports are processed per batch

emote/memory/memory.py, emote/trainer.py
We've had a shim for this exports in production, and I've noticed it can block early shutdowns since it won't check the shutdown signal.
=> Upgrade Memory Warmup callback to handle exports and early shutdowns

emote/extra/onnx_exporter.py
Repro'd and confirmed using the methodology here: https://github.com/pytorch/pytorch/issues/82532
We leak every single tensor in the model each iteration. I validated it by inserting the code from the above issue into test_htm_onnx and running `exporter.export` in a loop at the end. This is the objgraph growth per iteration:
```
tuple                16813       +44
dict                 13502       +23
ReferenceType         5569       +22
type                  3021       +22
Tensor                 340        +8
StorageItem             31        +1
StorageItemHandle       31        +1
```
Changing the code in this PR makes the growth only the following:
```
dict                 12921        +1
StorageItem            132        +1
StorageItemHandle      132        +1
```
=> work around memory leak in torch.jit.trace

emote/callbacks.py
There currently isn't the option to pick up from a certain `checkpoint_index` in `Checkpointer`. This can come in useful when wanting to load an existing checkpoint and keep training, adding further checkpoints later on.
=> Add `checkpointer_index` constructor argument to `Checkpointer`

emote/callbacks.py, tests/test_checkpoints.py
This allows optionally specifying the name of the subdirectory for the checkpointer and checkpointloader, with the default being "checkpoints". 
We also create the "checkpoints" subdirectory from here. 
This is done in emote to avoid code duplication in downstream projects and match our existing practices, and because 99% of the time, we want the subfolder to be called "checkpoints".
=> Add Storage Subdirectory

emote/optimizers.py, tests/test_modified_adamw.py
Creates a modified AdamW (that inherits from the standard AdamW) as suggested in _[Efficient deep reinforcement learning requires regulating overfitting](https://arxiv.org/pdf/2304.10466.pdf)_.
ModifiedAdamW disables weight decay for the bias, additional modules (such as LayerNorm), and specific named layers (e.g. the paper suggests excluding the final layer in the Q networks, which can be done by passing `layers_to_exclude = ["final_layer"]`). 
The function for separating the modules was adapted from a [PyTorch minGPT implementation](https://github.com/karpathy/minGPT/blob/3ed14b2cec0dfdad3f4b2831f2b4a86d11aef150/mingpt/model.py#L136) that is MIT licensed.
=> Add support for custom weight decay optimizer

emote/callbacks/checkpointing.py
Looks like `reset_training_steps` causes training to start at bp_steps=0 when True, not False
=> Fix simple doc error

.github/workflows/docs.yml, docs/callbacks.rst
This fixes a few missing classes and a missing graph in the docs.
=> fix docs build?

emote/sac.py
At the moment, we have agent proxies that support only one input key. These don't support the case of multiple parts in the observation, for example both features and images.
I wrote a new agent proxy that iterates through the given keys and creates a dictionary where all parts of the observation are stored with their respective keys. The policy can then handle these as needed.
Is this a good way to approach this?
=> Agent proxy that supports multiple input keys

emote/nn/curl.py, emote/nn/layers.py, tests/test_conv1denc.py
I added a Conv1d encoder which takes as input _(batch size, channels, length)_, or _(batch size, length, channels)_ if `channels_last=True`, following the example of the Con2d encoder. I also added the option to directly add a `nn.Flatten()` layer, instead of having to append one later on, but the _flatten_ parameter can be set to False if needed. 
Also, I updated the existing CURL callback to match the changes done to the Conv2d encoder.
=> Add Conv1d encoder and update Conv2d encoder with option to flatten

emote/callback.py, emote/callbacks/checkpointing.py, emote/callbacks/loss.py, emote/mixins/logging.py, tests/test_checkpoints.py
Made some updates to the Checkpointer and Checkpointloader as follows:
* Removed the extra input arguments for loading networks and optimizers. Now, you can only load a list of callbacks. However, added an additional input to the Checkpointloader class. When set to True, this input instructs the loader to exclusively load the neural network parameters, disregarding the state_dict of other callbacks. This feature is useful in scenarios where you need to copy a network from one callback to another or when you prefer not to load other callback parameters.
Both Checkpointer and Checkpointloader rely on a list of callbacks rather than a dictionary. To ensure the correct loading of callbacks, we store a corresponding list of names when saving the checkpoints. These names serve as references …
=> updating the checkpointer and checkpoint loader

emote/mixins/logging.py
For keys that override the default window length, we are separating the original key in two parts: the first one which gives us the length, and the second one which is the actual key we want to use for logging in the _windowed_scalar_ dictionary. For example, for a given key "_windowed[100]:**score**_", we will log using the key "_score_".
Next time that same value is sent to the logger, it is sent as "_windowed[100]:score_" again, but that key doesn't exist in the dictionary as we logged it using "_score_". So we enter the if-condition where we split the key, get "_score_" as the key we want to use for logging, and create a new deque with that key overwriting the data contained there previously.
By switching the order of the checks, we first split the key if it contains "_windowed[_" and …
=> Switch order of checks in log_windowed_scalar

emote/memory/memory.py, emote/mixins/logging.py
After fixing the overwriting problem in #148, I found that by logging using the split key we cause problems in other places where we request data from the dictionary. By the same logic as #148, when we want to get logged data we would request the original key, e.g. "windowed[100]:score" which doesn't exist in the dictionary, so we don't get any value back. Anything that depends on these values is then broken. 
Instead of splitting the key in a bunch of other places, this code uses the original key in the dictionary and then splits it only for logging to the writer.
=> Update windowed scalar (again)

emote/memory/memory.py
Why do we suffix this with inf-step? It gets very noisy and makes it much harder to compare the graphs between cog and emote. Could we remove it while we're debugging at least?
=> Remove _inf_step from tb logs

emote/nn/initialization.py
The current check raises RuntimeError: Boolean value of Tensor with more than one value is ambiguous
=> Change check for bias initialization

emote/callbacks/loss.py, emote/sac.py
This PR adds the ability to log per-parameter information, similar to what we had in Cog. It is opt-in and off by default.
See attached screenshot for examples of how it can look like.
=> add optional per-parameter logging for loss callbacks

.buildkite/Dockerfile, .buildkite/install-repo.sh, .buildkite/pipeline.yml, .buildkite/publish-docs.sh
Updates the base CI runner image to use pyenv to provide multiple python version using pyenv. 
This should allow us to reuse this image for all our repositories. See `install-repo.sh` for how to initialize pyenv and select a Python version.
=> setup multi-python image

emote/memory/memory.py, tests/test_memory_proxy_wrapper.py
This PR adds a `MemoryProxyWrapper` base class that all memory proxy wrappers should inherit from. This base class takes care of forwarding method calls that do not exist on the wrapper to the inner wrapped object. This solves problems where one would like to call a method existing on some inner wrapee but not on the outermost wrapper itself.
=> Make MemoryProxyWrappers forward methods to wrapee if they do not exist on wrapper

CHANGELOG.md, emote/callbacks/testing.py
Picking some changes from #150 to work towards landing that ~soon.
=> cherry-pick changes to reward-test-check

CHANGELOG.md, emote/extra/onnx_exporter.py, tests/test_onnx.py
This lets downstream users add things like configuration and hyperparameters.
We should probably ensure we can override the basic ONNX metadata as well at some point, but not sure about the API so ignoring for now.
```
model_proto.producer_name = "emote"
model_proto.domain = "dev.embark.ml"
model_proto.producer_version = self.version_tag
model_proto.model_version = model_version
model_proto.doc_string = "exported via Emote checkpointer"
```
=> add `OnnxExporter.add_metadata`

docs/callback.rst, emote/callback.py, emote/callbacks/checkpointing.py, emote/callbacks/logging.py, emote/callbacks/wb_logger.py, emote/memory/callbacks.py, emote/memory/memory.py, emote/trainer.py
This ensures there's no specific ordering required between modules in begin_training, a bug and/or footgun in our old frameworks.
=> split state restoration from begin_training

.buildkite/pipeline.yml, .buildkite/run-flake8.sh, .flake8, CHANGELOG.md, emote/callbacks/logging.py, emote/callbacks/wb_logger.py, emote/memory/memory.py, emote/models/model_env.py, emote/typing.py, emote/utils/threading.py, pdm.lock, pyproject.toml, tests/gym/dict_gym_wrapper.py, tests/test_mbrl.py, torch.lock
Normalizes CI between our repos, and we already have a checked in .flake8.
Also adds a `pdm run precommit` to run all tests and lints.
=> run flake8 on CI

experiments/gym/train_lunar_lander.py
The lunar lander trainer for SAC required a `policy` parameter for `create_train_callbacks()`, otherwise it wouldn't run. This PR fixes that.
=> Fix Lunar Lander Test

emote/callbacks/checkpointing.py, tests/test_checkpoints.py
Doesn't quite mirror [this cog PR](https://github.com/EmbarkStudios/cog/pull/731/files), but ensures we have the path, as discussed with @tgolsson. Please let me know in case I misunderstood something.
=> Add "latest_checkpoint" path to state_dict

emote/algorithms/sac.py, emote/extra/schedules.py, tests/test_sac.py
This PR adds support for entropy schedules in the AlphaLoss callback. Also I removed the multiplication term in the default target entropy value since it defaulted to a very small value (CC @AliGhadirzadeh) and now we have the option to set the target value directly instead of scaling the number of actions by changing `entropy_eps`.
=> Update AlphaLoss to support entropy schedules

emote/extra/onnx_exporter.py
We called this with a second argument that got ignored in onnx 1.14.1, but with 1.15.0, this is not legal anymore. Removing the second argument should fix this.
=> Fix wrong `onnx.load_model` arguments

emote/memory/memory.py, tests/test_memory_logger.py, tests/test_memory_proxy_wrapper.py
This PR:
* Adds an overrideable name to the memory TableMemoryProxy
* Exposes that name as a property
* Extends the proxy base to allowed reading properties from the inner classes
* Uses the above property for logging
=> fix bug in logging timers

.github/workflows/docs.yml, .github/workflows/pre-release.yaml, .github/workflows/release.yml
Since updating to python3.10, github actions failed as specifiying the python-version in the workflow files with only 3.10 got only parsed as 3.1. Setting this to 3.10.4 makes it find a proper build. 
This PR also separates the build-docs and deploy jobs, and runs the former whenever a PR is opened.
=> Update Github Workflows for Python3.10

emote/memory/memory.py, tests/test_memory_loading.py
This PR adds a `JointMemoryLoader` object that can sample data from multiple different `MemoryLoader`s. This is needed for a lot of imitation related training.
=> Add a joint memory loader capable of sampling data from multiple memory loaders

emote/memory/__init__.py
JointMemoryLoader is missing in the init file.
=> adding JointMemoryLoader to the init

emote/memory/storage.py, tests/test_next_n_element_wrapper.py
This PR adds a small virtual storage wrapper that samples the next `N` elements ahead. This is needed for AMP training where the policy does not execute actions at the same frequency as the imitation reference.
=> Add NextNElementWrapper virtual storage
